/**
 * Cloudflare Workers entrypoint (see wrangler.toml `main`).
 *
 * OpenNext's Cloudflare adapter only generates a `fetch` handler in
 * .open-next/worker.js. The cron sweep (see wrangler.toml `[triggers]`)
 * needs a `scheduled` handler exported alongside it, so this file wraps the
 * generated handler and adds one.
 */

// .open-next/worker.js is generated by `opennextjs-cloudflare build`: absent on
// a clean checkout, present once a build has run. @ts-expect-error only holds
// in the first state, since tsc reports it as an unused directive in the
// second, so the suppression has to be @ts-ignore, which next/typescript's
// ban-ts-comment rule then has to be told to allow.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import handler from "./.open-next/worker.js";
import { sweepExpiredReservations } from "./src/lib/db/sweep";

interface ScheduledEvent {
  cron: string;
  scheduledTime: number;
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

interface WorkerEnv {
  NEXT_PUBLIC_SUPABASE_URL: string;
  SUPABASE_SERVICE_ROLE_KEY: string;
  NEXT_PUBLIC_SITE_URL?: string;
  CRON_SECRET?: string;
  [binding: string]: unknown;
}

/** Cron pattern for the moderation retry sweep - must match wrangler.toml
 *  [triggers]. Any other pattern (the 5-minute one) runs the reservation sweep. */
const MODERATION_SWEEP_CRON = "11,26,41,56 * * * *";

const worker = {
  fetch: handler.fetch,

  async scheduled(event: ScheduledEvent, env: WorkerEnv, ctx: ExecutionContext): Promise<void> {
    // Demo/preview deploys ship a placeholder Supabase URL and no service-role
    // secret; running the sweeps there would just fail every tick.
    const supabaseUrl = env.NEXT_PUBLIC_SUPABASE_URL;
    const serviceRoleKey = env.SUPABASE_SERVICE_ROLE_KEY;
    if (!supabaseUrl || !serviceRoleKey || supabaseUrl.includes("placeholder")) {
      return;
    }

    if (event.cron === MODERATION_SWEEP_CRON) {
      // Retry the layer-2 (OpenAI) moderation check for sold cells whose
      // first attempt failed (moderation_checked_at still NULL). The logic
      // lives in the Next route; dispatch it through the worker's own fetch
      // handler with the shared cron secret, so there is exactly one
      // implementation of the sweep.
      const siteUrl = env.NEXT_PUBLIC_SITE_URL;
      const cronSecret = env.CRON_SECRET;
      if (!siteUrl || !cronSecret) {
        return;
      }
      ctx.waitUntil(
        handler.fetch(
          new Request(`${siteUrl}/api/cron/moderation-sweep`, {
            method: "POST",
            headers: { "x-cron-secret": cronSecret },
          }),
          env,
          ctx
        )
      );
      return;
    }

    // Safety-net sweep behind the event-driven checkout.session.expired
    // release path - see wrangler.toml [triggers] for the cadence rationale.
    ctx.waitUntil(sweepExpiredReservations(supabaseUrl, serviceRoleKey));
  },
};

export default worker;
